# 【問題1】ラグランジュの未定乗数法による最急降下
SVMの学習は、ラグランジュの未定乗数法を用います。サンプル数分のラグランジュ乗数 
λを用意して、以下の式により更新していきます。この計算を行うメソッドをScratchSVMClassifierクラスに実装してください。

$$
λ
n
e
w
i
=
λ
i
+
α
(
1
−
n
∑
j
=
1
λ
j
y
i
y
j
k
(
x
i
,
x
j
)
)
$$ 
ここで 
k
(
x
i
,
x
j
)
 はカーネル関数です。線形カーネルの場合は次のようになります。他のカーネル関数にも対応できるように、この部分は独立したメソッドとしておきましょう。

$$
k
(
x
i
,
x
j
)
=
x
T
i
x
j
$$
条件として、更新毎に 
λ
i
>=
0
を満たす必要があります。満たさない場合は 
λ
i
=
0
とします。


i
,
j
 : サンプルのインデックス


λ
n
e
w
i
 : 更新後のi番目のサンプルのラグランジュ乗数


λ
i
 : 更新前のi番目のサンプルのラグランジュ乗数


α
 : 学習率


λ
j
 : j番目のサンプルのラグランジュ乗数


y
i
 : i番目のサンプルのラベル


y
j
 : j番目のサンプルのラベル


x
i
 : i番目のサンプルの特徴量ベクトル


x
j
 : j番目のサンプルの特徴量ベクトル


あるサンプルに対しての全てのサンプルとの関係を計算していくことになります。



In [ ]:
class ScratchSVMClassifier():
    """
    SVM分類器のスクラッチ実装
    Parameters
    ----------
    num_iter : int
      イテレーション数
    lr : float
      学習率
    kernel : str
      カーネルの種類。線形カーネル（linear）か多項式カーネル（polly）
    threshold : float
      サポートベクターを選ぶための閾値
    verbose : bool
      学習過程を出力する場合はTrue
    Attributes
    ----------
    self.n_support_vectors : int
      サポートベクターの数（線を引く時の最小値の数）
    self.index_support_vectors : 次の形のndarray, shape (n_support_vectors,)
      サポートベクターのインデックス
    self.X_sv :  次の形のndarray, shape(n_support_vectors, n_features)
      サポートベクターの特徴量
    self.lam_sv :  次の形のndarray, shape(n_support_vectors, 1)
      サポートベクターの未定乗数
    self.y_sv :  次の形のndarray, shape(n_support_vectors, 1)
      サポートベクターのラベル
    """
    
    def __init__(self, num_iter, lr, kernel='linear', threshold=1e-5, verbose=False):
        # ハイパーパラメータを属性として記録
        self.iter = num_iter
        self.lr = lr
        self.kernel = kernel
        self.threshold = threshold
        self.verbose = verbose
        self.lam_sv = np.random.rand(X.shape[0], 1)
        
    def fit(self, X, y, X_val=None, y_val=None):
        """
        SVM分類器を学習する。検証データが入力された場合はそれに対する精度もイテレーションごとに計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データの特徴量
        y : 次の形のndarray, shape (n_samples, )
            訓練データの正解値
        X_val : 次の形のndarray, shape (n_samples, n_features)
            検証データの特徴量
        y_val : 次の形のndarray, shape (n_samples, )
            検証データの正解値
        """
        if self.verbose:
            #verboseをTrueにした際は学習過程を出力
            print()
        pass
    
    def predict(self, X):
        """
        SVM分類器を使いラベルを推定する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            サンプル
        Returns
        -------
            次の形のndarray, shape (n_samples, 1)
            SVM分類器による推定結果
        """
        pass
        return
    
    def gradient(self, X, error, y):
        self.lam_sv += self.lr*  
        

In [136]:
# 実験２　i,jをdiver通りにしてみる
# 結論　ぼつっぽい

lam_sv = np.random.rand(X.shape[0], 1)
def gradient(X, y, lr):
    iter = 1000
    y = y.reshape(-1,1)
    lam_sv = np.random.rand(X.shape[0], 1)
    
    for i in range(X.shape[0]):
        for j in range(X.shape[0]):
            calculation = (y[i]*y[j]*np.dot(X[i, 0].T,X[j, 1])) # iにするとreturnで止まるので無理
            #print(calculation.shape)
            delta = 1 - (np.sum(lam_sv[j]*calculation)) 
            lam_sv[i] += lam_sv[i]*delta # 更新されなくなるからぼつ
        return lam_sv

a = gradient(X, y, 0.01)
print(X.shape)
print(y.shape)

print(X[0,0].T*X[0,1])
d = (y[0].T*y[0]).reshape(-1,1)
lam_sv[0]
e = np.arange(0,30)
print((e * lam_sv[0]).shape)
a

(100, 2)
(100,)
0.27999999999999997
(30,)


array([[1.83586838],
       [0.20297189],
       [0.82386099],
       [0.68533949],
       [0.70877006],
       [0.45563699],
       [0.6765501 ],
       [0.4606542 ],
       [0.3635146 ],
       [0.92390147],
       [0.49984668],
       [0.37830757],
       [0.49509671],
       [0.07165763],
       [0.49291891],
       [0.38809107],
       [0.7669832 ],
       [0.17852004],
       [0.9341677 ],
       [0.47078122],
       [0.12132619],
       [0.84446086],
       [0.80261199],
       [0.36080166],
       [0.89480651],
       [0.68389975],
       [0.54770233],
       [0.2973395 ],
       [0.81101555],
       [0.54516682],
       [0.63186357],
       [0.55923333],
       [0.9676717 ],
       [0.01252031],
       [0.49184691],
       [0.97040796],
       [0.11713729],
       [0.19743757],
       [0.65839403],
       [0.39583634],
       [0.24523536],
       [0.03472239],
       [0.45991401],
       [0.61528861],
       [0.18359865],
       [0.78940649],
       [0.1599155 ],
       [0.902

In [101]:
# 実験１　独自で放り込む
def gradient(X, y, lr):
    iter = 1000
    y = y.reshape(-1,1)
    lam_sv = np.random.rand(X.shape[0], 1)
    
    for i in range(iter):
        for j in range(X.shape[0]):
            calculation = (T*y[j]*y[j].T*np.dot(X[j, 0].T,X[j, 1])).reshape(-1,1)
            delta = 1 - (np.sum(lam_sv.T*calculation))
            lam_sv[j] += lam_sv[j]*delta
        return lam_sv

a = gradient(X, y, 0.01)
print(X.shape)
print(y.shape)

print(X[0,0].T*X[0,1])
d = (y[0].T*y[0]).reshape(-1,1)


(100, 2)
(100,)
0.27999999999999997


array([[ 2.10671538e-01],
       [ 3.68615415e-01],
       [ 1.38376716e+00],
       [ 7.48631893e-01],
       [ 1.02462572e+00],
       [ 1.55359239e+00],
       [ 1.69267919e+00],
       [ 7.94031430e-01],
       [ 1.58205729e+00],
       [ 1.50850582e+00],
       [ 7.16146925e-01],
       [ 3.31443968e-01],
       [ 7.66372941e-01],
       [ 1.76088912e+00],
       [ 7.10031889e-01],
       [ 2.27013642e-01],
       [ 1.81526682e+00],
       [ 1.64792654e+00],
       [ 1.50930843e+00],
       [ 1.36460326e+00],
       [ 1.65819672e+00],
       [ 8.06258617e-01],
       [ 7.52648544e-01],
       [ 1.14840076e+00],
       [ 1.73403851e+00],
       [ 1.00330885e+00],
       [ 1.76856699e+00],
       [ 1.62232126e+00],
       [ 5.68763281e-01],
       [ 1.93698777e+00],
       [ 1.45228385e+00],
       [ 1.02958373e-01],
       [ 1.57504732e+00],
       [ 1.13663177e+00],
       [ 8.98041354e-01],
       [ 1.69352030e+00],
       [ 5.32561101e-01],
       [ 8.74347716e-01],
       [ 1.3

In [102]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
X = X.loc[:, ['petal length (cm)', 'petal width (cm)']][0:100].to_numpy()
y = iris.target[0:100]

a = np.random.rand(X.shape[0], 1)
b = np.arange(0,12).reshape(3,4)
c = np.arange(0,15).reshape(3,5)

In [24]:
import numpy
from matplotlib import pyplot
import sys

def f(x, y):
    return x - y

if __name__ == '__main__':

    param = sys.argv

    numpy.random.seed()
    N = 30
    d = 2
    X = numpy.random.randn(N, d)
    T = numpy.array([1 if f(x, y) > 0 else - 1 for x, y in X]) #sign関数
    alpha = numpy.zeros(N)
    beta = 1.0
    eta_al = 0.0001 # update ratio of alpha
    eta_be = 0.1 # update ratio of beta
    itr = 1000

    for _itr in range(itr):
        for i in range(N):
            delta = 1 - (T[i] * X[i]).dot(alpha * T * X.T).sum() - beta * T[i] * alpha.dot(T)
            alpha[i] += eta_al * delta
        for i in range(N):
            beta += eta_be * alpha.dot(T) ** 2 / 2

    index = alpha > 0
    w = (alpha * T).T.dot(X)
    b = (T[index] - X[index].dot(w)).mean()

    if '-d' in param or '-s' in param:
        seq = numpy.arange(-3, 3, 0.02)
        pyplot.figure(figsize = (6, 6))
        pyplot.xlim(-3, 3)
        pyplot.ylim(-3, 3)
        pyplot.plot(seq, -(w[0] * seq + b) / w[1], 'k-')
        pyplot.plot(X[T ==  1,0], X[T ==  1,1], 'ro')
        pyplot.plot(X[T == -1,0], X[T == -1,1], 'bo')

        if '-s' in param:
            pyplot.savefig('graph.png')

        if '-d' in param:
            pyplot.show()

In [15]:
X

array([[-0.86794486, -0.34632749],
       [ 1.02365263,  0.90059758],
       [-0.51188101, -0.5531725 ],
       [-0.95937369, -0.53097253],
       [ 1.32284448,  1.49926743],
       [ 1.21403215, -1.5245898 ],
       [ 0.68102778, -1.33557628],
       [-0.12646677, -0.31686371],
       [-0.76179442, -1.15764793],
       [ 0.78217355, -0.81697699],
       [-2.23396962, -0.55659711],
       [ 0.30036094,  0.08484028],
       [ 0.30881729,  1.04252214],
       [ 0.7214389 ,  0.03013635],
       [ 0.12860398,  0.10694267],
       [ 1.1790014 , -0.67207415],
       [-0.29225393, -2.71143776],
       [-1.33064361, -1.18637687],
       [ 0.41335843,  0.25750884],
       [ 0.51626022,  0.02681621],
       [-1.82204394,  0.19505924],
       [ 0.69038042, -1.22679068],
       [-0.08634655, -0.97368329],
       [-0.33546674,  1.23407074],
       [-0.91724022,  0.22096209],
       [ 0.82316319,  0.03330176],
       [-0.18515842,  0.56415186],
       [-0.85217527, -0.62682965],
       [ 0.00763205,