In [94]:
#メモ
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#アダマール積
a_ndarray * b_ndarray

array([[  0,   4,   3],
       [  0, -10, -48],
       [ 14,  72,   9]])

# 【問題1】行列積を手計算する

上記セルの１番上のa_ndarray,b_ndarrayの行列積を実施する。


[-1,2,3]    [0,2,1] =       [-1×0 + 2×0 + 3×2, -1×2 + 2×2 + 3×9, -1×1 + 2×-8 + 3×-1]<br>
[4,-5,6]   [0,2,-8] =     [4×0 + -5×0 + 6×2, 4×2 + -5×2 + 6×9, 4×1 + -5×-8 + 6×-1] <br>
[7,8,-9]    [2,9,-1] =      [7×0 + 8×0 + -9×2, 7×2 + 8×2 + -9×9, 7×1 + 8×8 + -9×-1]<br>

答え：<br>
[6, 29, -20]<br>
[12, 52, 38]<br>
[-18,-51,-48]<br>

後述：
基本的には左の行列は→、右の行列は↓の方向に進み、計算を行う。


In [95]:
# 問題２
# この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
# これらを使い行列積を計算してください。

'''
# matrixを使った行列計算
a_ndarray = np.matrix([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.matrix([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
'''

# 行列積
print(a_ndarray * b_ndarray)

# 行列積（matmul）
np.matmul(a_ndarray, b_ndarray)

[[  0   4   3]
 [  0 -10 -48]
 [ 14  72   9]]


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [96]:
# 問題３
# 手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
# この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。


#for文を使った要素を出力する計算式
list_amount = []
for i, j, k in a_ndarray:
    for x,y,z in b_ndarray.T:
        amount = (i * x + j * y + k * z)
        list_amount.append(amount)
              
np.array(list_amount).reshape(3,3)       


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [139]:
# 問題4
# 行列AとBを引数に受け取り、行列積を返す関数としてください。

def matrix_calculation(A, B):
    list_amount = []
    for i, j, k in A:
        for x,y,z in B.T:
            amount = (i * x + j * y + k * z)
            list_amount.append(amount)
    ndarray_list_amount = np.array(list_amount).reshape(3,3)
    return ndarray_list_amount

ndarray_list_amount = matrix_calculation(a_ndarray, b_ndarray)
ndarray_list_amount

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [143]:
# 問題5
# 問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります
# if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# 問題4にエラー検知を加えた関数
def matrix_calculation(A, B):
    if len(A[0,:]) == len(B[:,0]):
        list_amount = []
        for i, j, k in A:
            for x,y,z in B.T:
                amount = (i * x + j * y + k * z)
                list_amount.append(amount)
        ndarray_list_amount = np.array(list_amount).reshape(3,3)
        return ndarray_list_amount
    else:
        print("配列が正しくないため、計算できません")

matrix_calculation(d_ndarray, e_ndarray)

配列が正しくないため、計算できません


In [47]:
#  問題6
# 転置する

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
new_e_ndarray = e_ndarray.T

np.matmul(d_ndarray,new_e_ndarray)

array([[ 46,  -4],
       [-34,  73]])